language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"
before_script: composer install
script: phpunit --configuration tests/phpunit.xml
notifications:
    email:
        on_success: always
        on_failure: always

